services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - FLASK_DEBUG=1
    volumes:
     - ./src/:/app/src/
     - ./Makefile:/app/Makefile
    restart: always
    command: make start-fastapi

  mongo-sanbox:
    image: mongo:6.0
    container_name: mongo-sandbox
    ports:
      - 27020:27017

  mongo1:
    image: mongo:6.0
    container_name: mongo1
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip", "localhost,mongo1"]
    ports:
      - 27017:27017

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip", "localhost,mongo2"]
    ports:
      - 27018:27017

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip", "localhost,mongo3"]
    ports:
      - 27019:27017

  mongo-setup:
    image: mongo:6.0
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mongosh --host mongo1:27017 <<EOF
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongo1:27017' },
            { _id: 1, host: 'mongo2:27017' },
            { _id: 2, host: 'mongo3:27017' }
          ]
        });
        EOF
      "