services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - FLASK_DEBUG=1
    volumes:
      - ./src/:/app/src/
      - ./Makefile:/app/Makefile
    restart: always
    command: make start-fastapi

  worker:
    build: .
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - PUBSUB_PROJECT_ID=test-project
      - PUBSUB_SUBSCRIPTION_ID=ticket-events-sub
    volumes:
      - ./src/:/app/src/
      - ./Makefile:/app/Makefile
    restart: always
    command: make run-worker


  pubsub-emulator:
    image: google/cloud-sdk:latest
    container_name: pubsub-emulator
    command: >
      /bin/sh -c "gcloud beta emulators pubsub start --host-port=0.0.0.0:8085"
    ports:
      - 8085:8085
    environment:
      - PUBSUB_PROJECT_ID=test-project
    restart: always

  gcp-pubsub-emulator-ui:
    image: echocode/gcp-pubsub-emulator-ui:latest
    container_name: pubsub-explorer
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - GCP_PROJECT_IDS=test-project
    ports:
      - 8680:8680
    depends_on:
      - pubsub-emulator

  mongo-sandbox:
    image: mongo:6.0
    container_name: mongo-sandbox
    ports:
      - 27020:27017

  mongo1:
    image: mongo:6.0
    container_name: mongo1
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip", "localhost,mongo1"]
    ports:
      - 27017:27017

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip", "localhost,mongo2"]
    ports:
      - 27018:27017

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    entrypoint: ["mongod", "--replSet", "rs0", "--bind_ip", "localhost,mongo3"]
    ports:
      - 27019:27017

  mongo-setup:
    image: mongo:6.0
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mongosh --host mongo1:27017 <<EOF
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongo1:27017' },
            { _id: 1, host: 'mongo2:27017' },
            { _id: 2, host: 'mongo3:27017' }
          ]
        });
        EOF
      "