mongo:
  url: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
mongo_sandbox:
  url: mongodb://mongo-sandbox:27017
pubsub:
  emulator_host: pubsub-emulator:8085
  project_id: test-project
  topic_id: ticket-events